version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: matific
      MYSQL_PASSWORD: root
    networks:
      - backend

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '5000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend


  django:
    build: .
    command: bash -c "python manage.py makemigrations authentication && python manage.py makemigrations game && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./basketball_game_dashboard:/code
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
volumes:
  db_data: