# Generated by Django 3.2 on 2021-05-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='last_activity',
            field=models.DateTimeField(),
        ),
    ]
