# Generated by Django 3.2 on 2021-05-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userstat_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
