# Generated by Django 3.2 on 2021-05-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userstat_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
