# Generated by Django 3.2 on 2021-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userstat_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
