# Generated by Django 3.2 on 2021-05-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userstat_failed_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstat',
            name='failed_login_attempts',
        ),
    ]
